spring:
  profiles:
    active: dev
  application:
    name: "payment-gateway"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
logging:
  level:
    root: INFO
vaadin:
  compatibilityMode: false
coordinator:
  request-uri: "http://localhost:9123/accept?Content-Type=application/json"
  source-pattern: "http://localhost:80/v1/transaction/"
security:
  acquirer:
    username: SolanteqAcquirer
    password: q123456789?
---

server:
  port: 8080
spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow"
    username: "test"
    password: "test"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

coordinator:
  request-uri: "http://localhost:9123/accept?Content-Type=application/json"
  source-pattern: "http://localhost:8080/transaction/"

---

logging:
  level:
    root: INFO
  file:
    name: server.log
server:
  port: 80
spring:
  profiles: production
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=UTF-8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow"
    username: "test"
    password: "12345"
  jpa:
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: false

coordinator:
  request-uri: "http://localhost:9123/accept?Content-Type=application/json"
  source-pattern: "http://localhost:80/transaction/"